version: "3.8"
services:
  nginx:
    image: nginx:swarm
    ports: 
      - "80:80"
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  php:
    image: php:fpm-alpine
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
